### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by shincho0922** [shincho0922/protospace-34861#1]
#URL
https://protospace-34861.herokuapp.com/

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

### [修正依頼箇所]

- [x] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されるよう実装しましょう**

修正が完了しましたら、以下のprotospace完了報告フォームを再度ご提出ください。
※新しいissueを作っていただく必要はありません
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by shincho0922** [comment]
指摘項目の変更を行いましたのでご確認下さい。

**Comment by naru6117** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　**LGTMです✨**　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
